apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moon-web

resources:
  - ../../namespace.yaml
  - ../../micro-all/deployment.yaml
  - ../../micro-all/service.yaml
  - ../../micro-all/ingress.yaml
