apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moon-web

resources:
  - ../../namespace.yaml
  - ../../main/deployment.yaml
  - ../../main/service.yaml
  - ../../rabbit/deployment.yaml
  - ../../rabbit/service.yaml
  - ../../marksman/deployment.yaml
  - ../../marksman/service.yaml
  - ../../jade_tree/deployment.yaml
  - ../../jade_tree/service.yaml
  - ../../micro-composed/ingress.yaml
