apiVersion: apps/v1
kind: Deployment
metadata:
  name: moon-web-marksman
  namespace: moon-web
  labels:
    app.kubernetes.io/name: moon-web
    app.kubernetes.io/component: marksman
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: moon-web
      app.kubernetes.io/component: marksman
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moon-web
        app.kubernetes.io/component: marksman
    spec:
      containers:
        - name: web
          image: ghcr.io/aide-family/moon-web/marksman:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MOON_APP_NAME
              value: marksman
            - name: API_UPSTREAM
              value: http://moon-marksman-api.moon-api.svc.cluster.local:8003
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
