apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moon-web-integrated
  namespace: moon
  labels:
    app.kubernetes.io/name: moon-web
    app.kubernetes.io/component: integrated
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: kong
  rules:
    - host: moon.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moon-web-integrated
                port:
                  number: 80
  # tls:
  #   - hosts:
  #       - moon.example.com
  #     secretName: moon-web-tls
