apiVersion: v1
kind: Service
metadata:
  name: moon-web-integrated
  namespace: moon
  labels:
    app.kubernetes.io/name: moon-web
    app.kubernetes.io/component: integrated
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: moon-web
    app.kubernetes.io/component: integrated
  ports:
    - name: http
      port: 80
      targetPort: http
