/**
 * 数据源相关 API（策略管理服务，后端端口 8003）
 * 请求需带 Header：Authorization、X-Namespace（由 request 拦截器处理）
 */

import { http } from '../../index'
import type {
  DatasourceItem,
  DatasourceListParams,
  DatasourceListResponse,
  DatasourceSelectParams,
  DatasourceSelectResponse,
  CreateDatasourceParams,
  UpdateDatasourceParams,
  DatasourceMetricsResponse,
} from './types'
export type {
  DatasourceItem,
  DatasourceListParams,
  CreateDatasourceParams,
  UpdateDatasourceParams,
  MetricSummaryItem,
} from './types'
export { DatasourceType, DatasourceDriver } from './types'

/** 获取数据源列表 GET /v1/datasources */
export const getDatasourceList = (params?: DatasourceListParams): Promise<DatasourceListResponse> => {
  return http.get<DatasourceListResponse>('/datasources', params as unknown as Record<string, unknown>)
}

/** 获取数据源详情 GET /v1/datasource/{uid} */
export const getDatasourceDetail = (uid: string): Promise<DatasourceItem> => {
  return http.get<DatasourceItem>(`/datasource/${uid}`)
}

/** 创建数据源 POST /v1/datasource */
export const createDatasource = (params?: CreateDatasourceParams): Promise<DatasourceItem> => {
  return http.post<DatasourceItem>('/datasource', params as Record<string, unknown>)
}

/** 更新数据源 PUT /v1/datasource/{uid} */
export const updateDatasource = (uid: string, params?: UpdateDatasourceParams): Promise<DatasourceItem> => {
  return http.put<DatasourceItem>(`/datasource/${uid}`, params as Record<string, unknown>)
}

/** 删除数据源 DELETE /v1/datasource/{uid} */
export const deleteDatasource = (uid: string): Promise<Record<string, never>> => {
  return http.delete<Record<string, never>>(`/datasource/${uid}`)
}

/** 数据源选择列表（下拉等）GET /v1/datasources/select */
export const getDatasourceSelectList = (params?: DatasourceSelectParams): Promise<DatasourceSelectResponse> => {
  return http.get<DatasourceSelectResponse>('/datasources/select', params as unknown as Record<string, unknown>)
}

/** 获取数据源指标元数据 GET /v1/datasource/{uid}/metrics */
export const getDatasourceMetrics = (uid: string): Promise<DatasourceMetricsResponse> => {
  // return http.get<DatasourceMetricsResponse>(`/datasource/${uid}/metrics`)
  return Promise.resolve({
    "metrics": [
        {
            "name": "go_gc_cleanups_executed_cleanups_total",
            "description": "Approximate total count of cleanup functions (created by runtime.AddCleanup) executed by the runtime. Subtract /gc/cleanups/queued:cleanups to approximate cleanup queue length. Useful for detecting slow cleanups holding up the queue. Sourced from /gc/cleanups/executed:cleanups.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_cleanups_queued_cleanups_total",
            "description": "Approximate total count of cleanup functions (created by runtime.AddCleanup) queued by the runtime for execution. Subtract from /gc/cleanups/executed:cleanups to approximate cleanup queue length. Useful for detecting slow cleanups holding up the queue. Sourced from /gc/cleanups/queued:cleanups.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_cycles_automatic_gc_cycles_total",
            "description": "Count of completed GC cycles generated by the Go runtime. Sourced from /gc/cycles/automatic:gc-cycles.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_cycles_forced_gc_cycles_total",
            "description": "Count of completed GC cycles forced by the application. Sourced from /gc/cycles/forced:gc-cycles.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_cycles_total_gc_cycles_total",
            "description": "Count of all completed GC cycles. Sourced from /gc/cycles/total:gc-cycles.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_duration_seconds",
            "description": "A summary of the wall-time pause (stop-the-world) duration in garbage collection cycles.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "go_gc_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_finalizers_executed_finalizers_total",
            "description": "Total count of finalizer functions (created by runtime.SetFinalizer) executed by the runtime. Subtract /gc/finalizers/queued:finalizers to approximate finalizer queue length. Useful for detecting finalizers overwhelming the queue, either by being too slow, or by there being too many of them. Sourced from /gc/finalizers/executed:finalizers.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_finalizers_queued_finalizers_total",
            "description": "Total count of finalizer functions (created by runtime.SetFinalizer) and queued by the runtime for execution. Subtract from /gc/finalizers/executed:finalizers to approximate finalizer queue length. Useful for detecting slow finalizers holding up the queue. Sourced from /gc/finalizers/queued:finalizers.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_gogc_percent",
            "description": "Heap size target percentage configured by the user, otherwise 100. This value is set by the GOGC environment variable, and the runtime/debug.SetGCPercent function. Sourced from /gc/gogc:percent.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_gomemlimit_bytes",
            "description": "Go runtime memory limit configured by the user, otherwise math.MaxInt64. This value is set by the GOMEMLIMIT environment variable, and the runtime/debug.SetMemoryLimit function. Sourced from /gc/gomemlimit:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_heap_allocs_by_size_bytes_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_heap_allocs_by_size_bytes_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_heap_allocs_by_size_bytes_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_heap_allocs_bytes_total",
            "description": "Cumulative sum of memory allocated to the heap by the application. Sourced from /gc/heap/allocs:bytes.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_heap_allocs_objects_total",
            "description": "Cumulative count of heap allocations triggered by the application. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks. Sourced from /gc/heap/allocs:objects.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_heap_frees_by_size_bytes_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_heap_frees_by_size_bytes_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_heap_frees_by_size_bytes_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_heap_frees_bytes_total",
            "description": "Cumulative sum of heap memory freed by the garbage collector. Sourced from /gc/heap/frees:bytes.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_heap_frees_objects_total",
            "description": "Cumulative count of heap allocations whose storage was freed by the garbage collector. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks. Sourced from /gc/heap/frees:objects.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_heap_goal_bytes",
            "description": "Heap size target for the end of the GC cycle. Sourced from /gc/heap/goal:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_heap_live_bytes",
            "description": "Heap memory occupied by live objects that were marked by the previous GC. Sourced from /gc/heap/live:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_heap_objects_objects",
            "description": "Number of objects, live or unswept, occupying heap memory. Sourced from /gc/heap/objects:objects.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_heap_tiny_allocs_objects_total",
            "description": "Count of small allocations that are packed together into blocks. These allocations are counted separately from other allocations because each individual allocation is not tracked by the runtime, only their block. Each block is already accounted for in allocs-by-size and frees-by-size. Sourced from /gc/heap/tiny/allocs:objects.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_gc_limiter_last_enabled_gc_cycle",
            "description": "GC cycle the last time the GC CPU limiter was enabled. This metric is useful for diagnosing the root cause of an out-of-memory error, because the limiter trades memory for CPU time when the GC's CPU time gets too high. This is most likely to occur with use of SetMemoryLimit. The first GC cycle is cycle 1, so a value of 0 indicates that it was never enabled. Sourced from /gc/limiter/last-enabled:gc-cycle.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_pauses_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_pauses_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_pauses_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_gc_scan_globals_bytes",
            "description": "The total amount of global variable space that is scannable. Sourced from /gc/scan/globals:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_scan_heap_bytes",
            "description": "The total amount of heap space that is scannable. Sourced from /gc/scan/heap:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_scan_stack_bytes",
            "description": "The number of bytes of stack that were scanned last GC cycle. Sourced from /gc/scan/stack:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_scan_total_bytes",
            "description": "The total amount space that is scannable. Sum of all metrics in /gc/scan. Sourced from /gc/scan/total:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_gc_stack_starting_size_bytes",
            "description": "The stack size of new goroutines. Sourced from /gc/stack/starting-size:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_goroutines",
            "description": "Number of goroutines that currently exist.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_info",
            "description": "Information about the Go environment.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_alloc_bytes",
            "description": "Number of bytes allocated in heap and currently in use. Equals to /memory/classes/heap/objects:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_alloc_bytes_total",
            "description": "Total number of bytes allocated in heap until now, even if released already. Equals to /gc/heap/allocs:bytes.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_memstats_buck_hash_sys_bytes",
            "description": "Number of bytes used by the profiling bucket hash table. Equals to /memory/classes/profiling/buckets:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_frees_total",
            "description": "Total number of heap objects frees. Equals to /gc/heap/frees:objects + /gc/heap/tiny/allocs:objects.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_memstats_gc_sys_bytes",
            "description": "Number of bytes used for garbage collection system metadata. Equals to /memory/classes/metadata/other:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_heap_alloc_bytes",
            "description": "Number of heap bytes allocated and currently in use, same as go_memstats_alloc_bytes. Equals to /memory/classes/heap/objects:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_heap_idle_bytes",
            "description": "Number of heap bytes waiting to be used. Equals to /memory/classes/heap/released:bytes + /memory/classes/heap/free:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_heap_inuse_bytes",
            "description": "Number of heap bytes that are in use. Equals to /memory/classes/heap/objects:bytes + /memory/classes/heap/unused:bytes",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_heap_objects",
            "description": "Number of currently allocated objects. Equals to /gc/heap/objects:objects.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_heap_released_bytes",
            "description": "Number of heap bytes released to OS. Equals to /memory/classes/heap/released:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_heap_sys_bytes",
            "description": "Number of heap bytes obtained from system. Equals to /memory/classes/heap/objects:bytes + /memory/classes/heap/unused:bytes + /memory/classes/heap/released:bytes + /memory/classes/heap/free:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_last_gc_time_seconds",
            "description": "Number of seconds since 1970 of last garbage collection.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_mallocs_total",
            "description": "Total number of heap objects allocated, both live and gc-ed. Semantically a counter version for go_memstats_heap_objects gauge. Equals to /gc/heap/allocs:objects + /gc/heap/tiny/allocs:objects.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_memstats_mcache_inuse_bytes",
            "description": "Number of bytes in use by mcache structures. Equals to /memory/classes/metadata/mcache/inuse:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_mcache_sys_bytes",
            "description": "Number of bytes used for mcache structures obtained from system. Equals to /memory/classes/metadata/mcache/inuse:bytes + /memory/classes/metadata/mcache/free:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_mspan_inuse_bytes",
            "description": "Number of bytes in use by mspan structures. Equals to /memory/classes/metadata/mspan/inuse:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_mspan_sys_bytes",
            "description": "Number of bytes used for mspan structures obtained from system. Equals to /memory/classes/metadata/mspan/inuse:bytes + /memory/classes/metadata/mspan/free:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_next_gc_bytes",
            "description": "Number of heap bytes when next garbage collection will take place. Equals to /gc/heap/goal:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_other_sys_bytes",
            "description": "Number of bytes used for other system allocations. Equals to /memory/classes/other:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_stack_inuse_bytes",
            "description": "Number of bytes obtained from system for stack allocator in non-CGO environments. Equals to /memory/classes/heap/stacks:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_stack_sys_bytes",
            "description": "Number of bytes obtained from system for stack allocator. Equals to /memory/classes/heap/stacks:bytes + /memory/classes/os-stacks:bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_memstats_sys_bytes",
            "description": "Number of bytes obtained from system. Equals to /memory/classes/total:byte.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sched_gomaxprocs_threads",
            "description": "The current runtime.GOMAXPROCS setting, or the number of operating system threads that can execute user-level Go code simultaneously. Sourced from /sched/gomaxprocs:threads.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sched_goroutines_created_goroutines_total",
            "description": "Count of goroutines created since program start. Sourced from /sched/goroutines-created:goroutines.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_sched_goroutines_goroutines",
            "description": "Count of live goroutines. Sourced from /sched/goroutines:goroutines.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sched_goroutines_not_in_go_goroutines",
            "description": "Approximate count of goroutines running or blocked in a system call or cgo call. Not guaranteed to add up to /sched/goroutines:goroutines with other goroutine metrics. Sourced from /sched/goroutines/not-in-go:goroutines.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sched_goroutines_runnable_goroutines",
            "description": "Approximate count of goroutines ready to execute, but not executing. Not guaranteed to add up to /sched/goroutines:goroutines with other goroutine metrics. Sourced from /sched/goroutines/runnable:goroutines.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sched_goroutines_running_goroutines",
            "description": "Approximate count of goroutines executing. Always less than or equal to /sched/gomaxprocs:threads. Not guaranteed to add up to /sched/goroutines:goroutines with other goroutine metrics. Sourced from /sched/goroutines/running:goroutines.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sched_goroutines_waiting_goroutines",
            "description": "Approximate count of goroutines waiting on a resource (I/O or sync primitives). Not guaranteed to add up to /sched/goroutines:goroutines with other goroutine metrics. Sourced from /sched/goroutines/waiting:goroutines.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sched_latencies_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_latencies_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_latencies_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_stopping_gc_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_stopping_gc_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_stopping_gc_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_stopping_other_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_stopping_other_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_stopping_other_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_total_gc_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_total_gc_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_total_gc_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_total_other_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_total_other_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_pauses_total_other_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "go_sched_threads_total_threads",
            "description": "The current count of live threads that are owned by the Go runtime. Sourced from /sched/threads/total:threads.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "go_sync_mutex_wait_total_seconds_total",
            "description": "Approximate cumulative time goroutines have spent blocked on a sync.Mutex, sync.RWMutex, or runtime-internal lock. This metric is useful for identifying global changes in lock contention. Collect a mutex or block profile using the runtime/pprof package for more detailed contention data. Sourced from /sync/mutex/wait/total:seconds.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "go_threads",
            "description": "Number of OS threads created.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "marksman_datasource_status",
            "description": "Datasource health status from HTTP probe. 1 = healthy, 0 = unhealthy.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "net_conntrack_dialer_conn_attempted_total",
            "description": "Total number of connections attempted by the given dialer a given name.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "net_conntrack_dialer_conn_closed_total",
            "description": "Total number of connections closed which originated from the dialer of a given name.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "net_conntrack_dialer_conn_established_total",
            "description": "Total number of connections successfully established by the given dialer a given name.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "net_conntrack_dialer_conn_failed_total",
            "description": "Total number of connections failed to dial by the dialer a given name.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "net_conntrack_listener_conn_accepted_total",
            "description": "Total number of connections opened to the listener of a given name.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "net_conntrack_listener_conn_closed_total",
            "description": "Total number of connections closed that were made to the listener of a given name.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "process_cpu_seconds_total",
            "description": "Total user and system CPU time spent in seconds.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "process_max_fds",
            "description": "Maximum number of open file descriptors.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "process_network_receive_bytes_total",
            "description": "Number of bytes received by the process over the network.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "process_network_transmit_bytes_total",
            "description": "Number of bytes sent by the process over the network.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "process_open_fds",
            "description": "Number of open file descriptors.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "process_resident_memory_bytes",
            "description": "Resident memory size in bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "process_start_time_seconds",
            "description": "Start time of the process since unix epoch in seconds.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "process_virtual_memory_bytes",
            "description": "Virtual memory size in bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "process_virtual_memory_max_bytes",
            "description": "Maximum amount of virtual memory available in bytes.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_api_notification_active_subscribers",
            "description": "The current number of active notification subscribers.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_api_notification_updates_dropped_total",
            "description": "Total number of notification updates dropped.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_api_notification_updates_sent_total",
            "description": "Total number of notification updates sent.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_build_info",
            "description": "A metric with a constant '1' value labeled by version, revision, branch, goversion from which prometheus was built, and the goos and goarch for the build.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_config_last_reload_success_timestamp_seconds",
            "description": "Timestamp of the last successful configuration reload.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_config_last_reload_successful",
            "description": "Whether the last configuration reload attempt was successful.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_engine_queries",
            "description": "The current number of queries being executed or waiting.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_engine_queries_concurrent_max",
            "description": "The max number of concurrent queries.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_engine_query_duration_histogram_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_engine_query_duration_histogram_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_engine_query_duration_histogram_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_engine_query_duration_seconds",
            "description": "Query timings",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_engine_query_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_engine_query_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_engine_query_log_enabled",
            "description": "State of the query log.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_engine_query_log_failures_total",
            "description": "The number of query log failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_engine_query_samples_total",
            "description": "The total number of samples loaded by all queries.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_http_request_duration_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_http_request_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_http_request_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_http_requests_total",
            "description": "Counter of HTTP requests.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_http_response_size_bytes_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_http_response_size_bytes_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_http_response_size_bytes_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_notifications_alertmanagers_discovered",
            "description": "The number of alertmanagers discovered and active.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_notifications_queue_capacity",
            "description": "The capacity of the alert notifications queue.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_ready",
            "description": "Whether Prometheus startup was fully completed and the server is ready for normal operation.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_remote_read_handler_queries",
            "description": "The current number of remote read queries that are either in execution or queued on the handler.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_remote_storage_exemplars_in_total",
            "description": "Exemplars in to remote storage, compare to exemplars out for queue managers. Deprecated, check prometheus_wal_watcher_records_read_total and prometheus_remote_storage_exemplars_dropped_total",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_remote_storage_highest_timestamp_in_seconds",
            "description": "Highest timestamp that has come into the remote storage via the Appender interface, in seconds since epoch. Initialized to 0 when no data has been received yet. Deprecated, check prometheus_remote_storage_queue_highest_timestamp_seconds which is more accurate.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_remote_storage_histograms_in_total",
            "description": "HistogramSamples in to remote storage, compare to histograms out for queue managers. Deprecated, check prometheus_wal_watcher_records_read_total and prometheus_remote_storage_histograms_dropped_total",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_remote_storage_samples_in_total",
            "description": "Samples in to remote storage, compare to samples out for queue managers. Deprecated, check prometheus_wal_watcher_records_read_total and prometheus_remote_storage_samples_dropped_total",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_remote_storage_string_interner_zero_reference_releases_total",
            "description": "The number of times release has been called for strings that are not interned.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_rule_evaluation_duration_histogram_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_evaluation_duration_histogram_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_evaluation_duration_histogram_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_evaluation_duration_seconds",
            "description": "The duration for a rule to execute.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_rule_evaluation_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_evaluation_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_group_duration_histogram_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_group_duration_histogram_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_group_duration_histogram_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_group_duration_seconds",
            "description": "The duration of rule group evaluations.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_rule_group_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_rule_group_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_sd_azure_cache_hit_total",
            "description": "Number of cache hit during refresh.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_azure_failures_total",
            "description": "Number of Azure service discovery refresh failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_consul_rpc_duration_seconds",
            "description": "The duration of a Consul RPC call in seconds.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_sd_consul_rpc_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_sd_consul_rpc_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_sd_consul_rpc_failures_total",
            "description": "The number of Consul RPC call failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_discovered_targets",
            "description": "Current number of discovered targets.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_sd_dns_lookup_failures_total",
            "description": "The number of DNS-SD lookup failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_dns_lookups_total",
            "description": "The number of DNS-SD lookups.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_failed_configs",
            "description": "Current number of service discovery configurations that failed to load.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_sd_file_read_errors_total",
            "description": "The number of File-SD read errors.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_file_scan_duration_seconds",
            "description": "The duration of the File-SD scan in seconds.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_sd_file_scan_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_sd_file_scan_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_sd_file_watcher_errors_total",
            "description": "The number of File-SD errors caused by filesystem watch failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_http_failures_total",
            "description": "Number of HTTP service discovery refresh failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_kubernetes_events_total",
            "description": "The number of Kubernetes events handled.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_kubernetes_failures_total",
            "description": "The number of failed WATCH/LIST requests.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_kuma_fetch_duration_seconds",
            "description": "The duration of a Kuma MADS fetch call.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_sd_kuma_fetch_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_sd_kuma_fetch_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_sd_kuma_fetch_failures_total",
            "description": "The number of Kuma MADS fetch call failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_kuma_fetch_skipped_updates_total",
            "description": "The number of Kuma MADS fetch calls that result in no updates to the targets.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_linode_failures_total",
            "description": "Number of Linode service discovery refresh failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_nomad_failures_total",
            "description": "Number of nomad service discovery refresh failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_received_updates_total",
            "description": "Total number of update events received from the SD providers.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_updates_delayed_total",
            "description": "Total number of update events that couldn't be sent immediately.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_sd_updates_total",
            "description": "Total number of update events sent to the SD consumers.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_interval_length_histogram_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_interval_length_histogram_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_interval_length_histogram_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_interval_length_seconds",
            "description": "Actual intervals between scrapes.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_target_interval_length_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_interval_length_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_metadata_cache_bytes",
            "description": "The number of bytes that are currently used for storing metric metadata in the cache",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_target_metadata_cache_entries",
            "description": "Total number of metric metadata entries in the cache",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_target_scrape_duration_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_scrape_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_scrape_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_scrape_pool_exceeded_label_limits_total",
            "description": "Total number of times scrape pools hit the label limits, during sync or config reload.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrape_pool_exceeded_target_limit_total",
            "description": "Total number of times scrape pools hit the target limit, during sync or config reload.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrape_pool_reloads_failed_total",
            "description": "Total number of failed scrape pool reloads.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrape_pool_reloads_total",
            "description": "Total number of scrape pool reloads.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrape_pool_symboltable_items",
            "description": "Current number of symbols in table for this scrape pool.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_target_scrape_pool_sync_total",
            "description": "Total number of syncs that were executed on a scrape pool.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrape_pool_target_limit",
            "description": "Maximum number of targets allowed in this scrape pool.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_target_scrape_pool_targets",
            "description": "Current number of targets in this scrape pool.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_target_scrape_pools_failed_total",
            "description": "Total number of scrape pool creations that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrape_pools_total",
            "description": "Total number of scrape pool creation attempts.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_cache_flush_forced_total",
            "description": "How many times a scrape cache was flushed due to getting big while scrapes are failing.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_exceeded_body_size_limit_total",
            "description": "Total number of scrapes that hit the body size limit",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_exceeded_native_histogram_bucket_limit_total",
            "description": "Total number of scrapes that hit the native histogram bucket limit and were rejected.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_exceeded_sample_limit_total",
            "description": "Total number of scrapes that hit the sample limit and were rejected.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_exemplar_out_of_order_total",
            "description": "Total number of exemplar rejected due to not being out of the expected order.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_sample_duplicate_timestamp_total",
            "description": "Total number of samples rejected due to duplicate timestamps but different values.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_sample_out_of_bounds_total",
            "description": "Total number of samples rejected due to timestamp falling outside of the time bounds.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_scrapes_sample_out_of_order_total",
            "description": "Total number of samples rejected due to not being out of the expected order.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_sync_failed_total",
            "description": "Total number of target sync failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_target_sync_length_histogram_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_sync_length_histogram_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_sync_length_histogram_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_sync_length_seconds",
            "description": "Actual interval to sync the scrape pool.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_target_sync_length_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_target_sync_length_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_template_text_expansion_failures_total",
            "description": "The total number of template text expansion failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_template_text_expansions_total",
            "description": "The total number of template text expansions.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_treecache_watcher_goroutines",
            "description": "The current number of watcher goroutines.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_treecache_zookeeper_failures_total",
            "description": "The total number of ZooKeeper failures.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_blocks_loaded",
            "description": "Number of currently loaded data blocks",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_checkpoint_creations_failed_total",
            "description": "Total number of checkpoint creations that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_checkpoint_creations_total",
            "description": "Total number of checkpoint creations attempted.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_checkpoint_deletions_failed_total",
            "description": "Total number of checkpoint deletions that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_checkpoint_deletions_total",
            "description": "Total number of checkpoint deletions attempted.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_clean_start",
            "description": "-1: lockfile is disabled. 0: a lockfile from a previous execution was replaced. 1: lockfile creation was clean",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_range_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_range_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_range_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_samples_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_samples_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_samples_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_size_bytes_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_size_bytes_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_chunk_size_bytes_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_duration_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_compaction_populating_block",
            "description": "Set to 1 when a block is currently being written to the disk.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_compactions_failed_total",
            "description": "Total number of compactions that failed for the partition.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_compactions_skipped_total",
            "description": "Total number of skipped compactions due to disabled auto compaction.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_compactions_total",
            "description": "Total number of compactions that were executed for the partition.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_compactions_triggered_total",
            "description": "Total number of triggered compactions for the partition.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_data_replay_duration_seconds",
            "description": "Time taken to replay the data on disk.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_exemplar_exemplars_appended_total",
            "description": "Total number of appended exemplars.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_exemplar_exemplars_in_storage",
            "description": "Number of exemplars currently in circular storage.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_exemplar_last_exemplars_timestamp_seconds",
            "description": "The timestamp of the oldest exemplar stored in circular storage. Useful to check for what timerange the current exemplar buffer limit allows. This usually means the last timestampfor all exemplars for a typical setup. This is not true though if one of the series timestamp is in future compared to rest series.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_exemplar_max_exemplars",
            "description": "Total number of exemplars the exemplar storage can store, resizeable.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_exemplar_out_of_order_exemplars_total",
            "description": "Total number of out of order exemplar ingestion failed attempts.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_exemplar_series_with_exemplars_in_storage",
            "description": "Number of series with exemplars currently in circular storage.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_active_appenders",
            "description": "Number of currently active appender transactions",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_chunks",
            "description": "Total number of chunks in the head block.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_chunks_created_total",
            "description": "Total number of chunks created in the head",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_chunks_removed_total",
            "description": "Total number of chunks removed in the head",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_chunks_storage_size_bytes",
            "description": "Size of the chunks_head directory.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_gc_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_head_gc_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_head_max_time",
            "description": "Maximum timestamp of the head block. The unit is decided by the library consumer.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_max_time_seconds",
            "description": "Maximum timestamp of the head block.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_min_time",
            "description": "Minimum time bound of the head block. The unit is decided by the library consumer.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_min_time_seconds",
            "description": "Minimum time bound of the head block.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_out_of_order_samples_appended_total",
            "description": "Total number of appended out of order samples.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_samples_appended_total",
            "description": "Total number of appended samples.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_series",
            "description": "Total number of series in the head block.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_series_created_total",
            "description": "Total number of series created in the head",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_series_not_found_total",
            "description": "Total number of requests for series that were not found.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_series_removed_total",
            "description": "Total number of series removed in the head",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_stale_series",
            "description": "Total number of stale series in the head block.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_head_truncations_failed_total",
            "description": "Total number of head truncations that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_head_truncations_total",
            "description": "Total number of head truncations attempted.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_isolation_high_watermark",
            "description": "The highest TSDB append ID that has been given out.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_isolation_low_watermark",
            "description": "The lowest TSDB append ID that is still referenced.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_lowest_timestamp",
            "description": "Lowest timestamp value stored in the database. The unit is decided by the library consumer.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_lowest_timestamp_seconds",
            "description": "Lowest timestamp value stored in the database.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_mmap_chunk_corruptions_total",
            "description": "Total number of memory-mapped chunk corruptions.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_mmap_chunks_total",
            "description": "Total number of chunks that were memory-mapped.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_out_of_bound_samples_total",
            "description": "Total number of out of bound samples ingestion failed attempts with out of order support disabled.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_out_of_order_samples_total",
            "description": "Total number of out of order samples ingestion failed attempts due to out of order being disabled.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_reloads_failures_total",
            "description": "Number of times the database failed to reloadBlocks block data from disk.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_reloads_total",
            "description": "Number of times the database reloaded block data from disk.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_retention_limit_bytes",
            "description": "Max number of bytes to be retained in the tsdb blocks, configured 0 means disabled",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_retention_limit_seconds",
            "description": "How long to retain samples in storage.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_sample_ooo_delta_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_sample_ooo_delta_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_sample_ooo_delta_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_size_retentions_total",
            "description": "The number of times that blocks were deleted because the maximum number of bytes was exceeded.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_snapshot_replay_error_total",
            "description": "Total number snapshot replays that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_stale_series_compaction_duration_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_stale_series_compaction_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_stale_series_compaction_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_stale_series_compactions_failed_total",
            "description": "Total number of stale series compactions that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_stale_series_compactions_triggered_total",
            "description": "Total number of triggered stale series compactions.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_storage_blocks_bytes",
            "description": "The number of bytes that are currently used for local storage by all blocks.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_symbol_table_size_bytes",
            "description": "Size of symbol table in memory for loaded blocks",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_time_retentions_total",
            "description": "The number of times that blocks were deleted because the maximum time limit was exceeded.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_tombstone_cleanup_seconds_bucket",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_tombstone_cleanup_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_tombstone_cleanup_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_too_old_samples_total",
            "description": "Total number of out of order samples ingestion failed attempts with out of support enabled, but sample outside of time window.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_vertical_compactions_total",
            "description": "Total number of compactions done on overlapping blocks.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_completed_pages_total",
            "description": "Total number of completed pages.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_corruptions_total",
            "description": "Total number of WAL corruptions.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_fsync_duration_seconds",
            "description": "Duration of write log fsync.",
            "unit": "",
            "type": "summary"
        },
        {
            "name": "prometheus_tsdb_wal_fsync_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_wal_fsync_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_wal_page_flushes_total",
            "description": "Total number of page flushes.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_record_bytes_saved_total",
            "description": "Total number of bytes saved by the optional record compression. Use this metric to learn about the effectiveness compression.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_record_part_writes_total",
            "description": "Total number of record parts written before flushing.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_record_parts_bytes_written_total",
            "description": "Total number of record part bytes written before flushing, including CRC and compression headers.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_segment_current",
            "description": "Write log segment index that TSDB is currently writing to.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_wal_storage_size_bytes",
            "description": "Size of the write log directory.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "prometheus_tsdb_wal_truncate_duration_seconds_count",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_wal_truncate_duration_seconds_sum",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "prometheus_tsdb_wal_truncations_failed_total",
            "description": "Total number of write log truncations that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_truncations_total",
            "description": "Total number of write log truncations attempted.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_tsdb_wal_writes_failed_total",
            "description": "Total number of write log writes that failed.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_web_federation_errors_total",
            "description": "Total number of errors that occurred while sending federation responses.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "prometheus_web_federation_warnings_total",
            "description": "Total number of warnings that occurred while sending federation responses.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "promhttp_metric_handler_requests_in_flight",
            "description": "Current number of scrapes being served.",
            "unit": "",
            "type": "gauge"
        },
        {
            "name": "promhttp_metric_handler_requests_total",
            "description": "Total number of scrapes by HTTP status code.",
            "unit": "",
            "type": "counter"
        },
        {
            "name": "scrape_duration_seconds",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "scrape_samples_post_metric_relabeling",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "scrape_samples_scraped",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "scrape_series_added",
            "description": "",
            "unit": "",
            "type": ""
        },
        {
            "name": "up",
            "description": "",
            "unit": "",
            "type": ""
        }
    ]
})
}
