apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moon-web-goddess
  namespace: moon
  labels:
    app.kubernetes.io/name: moon-web
    app.kubernetes.io/component: goddess
spec:
  ingressClassName: kong
  rules:
    - host: goddess.moon.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moon-web-goddess
                port:
                  number: 80
