name: Docker Build and Push

on:
  push:
    tags:
      - 'v*' # 触发条件可以根据你的需求修改

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.REPO_PASS }}" | docker login -u "${{ secrets.REPO }}" --password-stdin

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --always)
          echo "Latest tag is $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Build and push Docker image
        run: |
          chmod +x build_images.sh
          ./build_images.sh "${{ secrets.REPO }}"
          
        env:
          REPO: ${{ secrets.REPO }}
          REPO_PASS: ${{ secrets.REPO_PASS }}
      
            - name: Send Release Notification
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json"  -d '{"msg_type":"post","content":{"post":{"zh_cn":{"title":"moon项目更新通知","content":[[{"tag":"text","text":"moon-frontend项目有更新, 当前版本为: "},{"tag":"a","text":"${{ steps.get_latest_tag.outputs.latest_tag }}","href":"https://hub.docker.com/r/aidemoonio/palace/tags?name=${{ steps.get_latest_tag.outputs.latest_tag }}"}],[],[{"tag":"at","user_id":"all"}]]}}}}' ${{ secrets.HOOK }}
